FROM ubuntu:latest
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install vim git zsh curl fonts-powerline python3.10 \
    && chsh -s $(which zsh)
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

RUN git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

